sudo: false
language: generic

#services:
#  - docker

addons:
  apt:
    packages:
      - fakeroot
      - lintian

#before_install:
#  - sudo apt-get install fakeroot lintian
#  - ./debianization.sh 0.1.0 stretch
#  - docker pull debian:stretch
#  - docker run debian:stretch /bin/sh -c "apt-get install fakeroot"

script:
  - cd deb
  - /bin/sh ./debianization.sh 0.1.0 squeeze
  - lintian deb_packages/freenetis-monitoring_0.1.0+squeeze.deb
  - /bin/sh ./debianization.sh 0.1.0 wheezy
  - lintian deb_packages/freenetis-monitoring_0.1.0+wheezy.deb
  - /bin/sh ./debianization.sh 0.1.0 stretch
  - lintian deb_packages/freenetis-monitoring_0.1.0+stretch.deb
