sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker pull debian:stretch
  - docker run debian:stretch /bin/sh -c "apt-get install fakeroot"

script:
  - ./debianization.sh 0.1.0 stretch
